name: Build Jenkins Image

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  packer-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packer
        uses: hashicorp/setup-packer@main

      - name: Run `packer init`
        id: init
        run: packer init packer

      - name: Run packer fmt
        run: |
          output=$(packer fmt packer)
          if [ -n "$output" ]; then
             echo "$output"
             exit 1
          fi

      - name: Run packer validate
        run: packer validate .

      - name: Run packer build
        run: packer build .
